### ISSUE TITLE
OVH Plugin : TroubleShouting DNS

### ISSUE THREAD

**Issue by Naehs** [rmbolger/Posh-ACME#147]
Hello,

First of all, thanks for your work and this Plugin ! :) 

I'm trying since days to create a wildcard certificate with OVH Plugin.
But it seems that Posh-ACME have some troubles to get my domain zone : https://eu.api.ovh.com/1.0/domain/zone/sydcrc.online

Error :
You will find the global process with -Verbose and -Debug in attachment.
```
Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
COMMENTAIRES : GET https://eu.api.ovh.com/1.0/domain/zone/sydcrc.online with 0-byte payload
DÉBOGUER : OVH Error: Le serveur distant a retourné une erreur : (400) Demande incorrecte.

Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
No zone found for _acme-challenge.sydcrc.online
Au caractère C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.4.0\DnsPlugins\OVH.ps1:343 : 5
+     throw "No zone found for $RecordName"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No zone found f...e.sydcrc.online:String) [], RuntimeException
    + FullyQualifiedErrorId : No zone found for _acme-challenge.sydcrc.online
```

I've tried out the query with [OVH Console](https://eu.api.ovh.com/console/#/domain/zone/%7BzoneName%7D#GET) and [OVH Official PHP Library](https://github.com/ovh/php-ovh) on my Server, and it works well. It returns my DNS.

I know this library works because i've used it last week on an other Server.
But on this one, it did not work ! :(

An help would be welcome.

Loïc.

PS: I saw last update for OVH Plugin (25/05), i've reinstalled Posh-ACME but this error persists.

[OVH.txt](https://github.com/rmbolger/Posh-ACME/files/3224461/OVH.txt)

**Comment by rmbolger** [comment]
Just wanted to let you know I started looking into this a bit but haven't found anything conclusive yet. Is the the sydcrc.online domain registered in the same OVH region as the other domain that worked?

**Comment by Naehs** [comment]
Thanks for your return.

Server A : Server where Posh-ACME worked perfectly for another domain.
Server B : The one who have some troubles.
_________

Server A : PowerShell = 5.1.14409.1005

I got the 2 minutes DNS delay.
Then i got the same error, but it worked !

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> New-PACertificate *.sydcrc.online -AcceptTOS -Contact support.crc@syd.fr -DnsPlugin OVH -PluginA
rgs $pArgs

cmdlet Add-DnsTxtOVH at command pipeline position 1
Supply values for the following parameters:
OVHAppKey: bMldyjfxEor1c3FN
OVHAppSecret: ********************************
OVHConsumerKey: ********************************
Remove-DnsTxtOVH : Parameter set cannot be resolved using the specified named parameters.
At C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.4.0\Public\Unpublish-DNSChallenge.ps1:38 char:5
+     &$delCommand -RecordName $recordName -TxtValue $txtValue @PluginA ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-DnsTxtOVH], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Remove-DnsTxtOVH


Subject            NotAfter            KeyLength Thumbprint                               AllSANs
-------            --------            --------- ----------                               -------
CN=*.sydcrc.online 27/08/2019 15:52:33 2048      A20CA98BC055769B1949EF6E0406CBFE6C92EB98 {*.sydcrc.online}


PS C:\Windows\system32>
```

Server B : PowerShell = 5.1.14393.2969

DNS delay appeared like 0.5 second, then the error is prompted.

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Tous droits réservés.

PS C:\Windows\system32> New-PACertificate *.sydcrc.online -AcceptTOS -Contact support.crc@syd.fr -DnsPlugin OVH -PluginA
rgs $pArgs
No zone found for _acme-challenge.sydcrc.online
Au caractère C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.4.0\DnsPlugins\OVH.ps1:343 : 5
+     throw "No zone found for $RecordName"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No zone found f...e.sydcrc.online:String) [], RuntimeException
    + FullyQualifiedErrorId : No zone found for _acme-challenge.sydcrc.online

PS C:\Windows\system32>
```
_________

Well i seems like Server B have a problem but i do the same steps, Server B can get domain zone info directly with the PHP Library, so in my opinion there is no trouble for communications.
On this Server, OVH API returns a HTTP 400 Bad Request, it may be related to the credential declaration explained below ?

For information, on Server B i use "Windows and PS 6.2 and later" way even if my PowerShell is under 6.1 because the "Non-Windows PS 6.1 and earlier" prompt an error.

```
$appSecret = Read-Host -Prompt "App Secret" -AsSecureString
$consumerKey = Read-Host -Prompt "Consumer Key" -AsSecureString
$pArgs = @{
    OVHAppKey = 'xxxxxxxxxxx'
    OVHAppSecret = $appSecret
    OVHConsumerKey = $consumerKey
    OVHRegion = 'ovh-eu'
}
New-PACertificate test.example.com -DnsPlugin OVH -PluginArgs $pArgs
```

On Server A i remember to have used the "Non-Windows PS 6.1 and earlier" way.

Loïc.

**Comment by rmbolger** [comment]
Oh no. I made a mistake in the readme example for the Non-Windows PS 6.1 and earlier (which I just fixed). If you're not using the SecureString versions of the app secret and consumer key, you need to specify the parameters as `OVHAppSecretInsecure` and `OVHConsumerKeyInsecure` like this:

```
$pArgs = @{
    OVHAppKey = 'xxxxxxxxxxxx'
    OVHAppSecretInsecure = 'yyyyyyyyyyyy'
    OVHConsumerKeyInsecure = 'zzzzzzzzzzzz'
    OVHRegion = 'ovh-eu'
}
```

But since both of your servers are on Windows, you can use either version of the parameters.

Your Server A example is strange even though it worked. It looks like you supplied `$pArgs`, but it still prompted you for the required parameters as-if it was null. That might be because of the incorrect parameter names from the read me though.

I'm curious what happens if you try again using the "insecure" parameter method.

I'm going to test some more on my end as well.

**Comment by rmbolger** [comment]
Also, here's a quick way to test just the plugin parameters rather than needing to actually generate a cert. This will attempt to create and delete a fake DNS challenge record. If these work, using `New-PACertificate` with the same `$pArgs` should work too.

```
Publish-DNSChallenge example.com (Get-PAAccount) test OVH $pArgs -verbose
Unpublish-DNSChallenge example.com (Get-PAAccount) test OVH $pArgs -verbose
```

**Comment by Naehs** [comment]
Thanks for your time.

______
Publish-DNSChallenge *.sydcrc.online (Get-PAAccount) test OVH $pArgs -Verbose -Debug
```
PS C:\Windows\system32> Publish-DNSChallenge *.sydcrc.online (Get-PAAccount) test OVH $pArgs -Verbose -Debug
DÉBOGUER : Loading PAAccount list from disk

Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
DÉBOGUER : Calling OVH plugin to add _acme-challenge.*.sydcrc.online TXT with value
D9wnCD63eE_R_Aubgn7zhrL2OXr48P25Xe1katZn5FQ

Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
COMMENTAIRES : GET
https://eu.api.ovh.com/1.0/domain/zone/sydcrc.online/record?fieldType=TXT&subDomain=_acme-challenge.* with 0-byte
payload
COMMENTAIRES : received 2-byte response of content type application/json; charset=utf-8
COMMENTAIRES : Adding a TXT record for _acme-challenge.*.sydcrc.online with value
D9wnCD63eE_R_Aubgn7zhrL2OXr48P25Xe1katZn5FQ
COMMENTAIRES : POST https://eu.api.ovh.com/1.0/domain/zone/sydcrc.online/record with -1-byte payload
Invoke-RestMethod : {"message":"Invalid domain name: _acme-challenge.*.sydcrc.online"}
Au caractère C:\Program Files\WindowsPowerShell\Modules\Posh-ACME\3.4.0\DnsPlugins\OVH.ps1:310 : 5
+     Invoke-RestMethod @restArgs @script:UseBasic -EA Stop
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebEx
   ception
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
PS C:\Windows\system32>
```
______
Unpublish-DNSChallenge *.sydcrc.online (Get-PAAccount) test OVH $pArgs -Verbose -Debug
```
PS C:\Windows\system32> Unpublish-DNSChallenge *.sydcrc.online (Get-PAAccount) test OVH $pArgs -Verbose -Debug
DÉBOGUER : Loading PAAccount list from disk

Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
DÉBOGUER : Calling OVH plugin to remove _acme-challenge.*.sydcrc.online TXT with value
D9wnCD63eE_R_Aubgn7zhrL2OXr48P25Xe1katZn5FQ

Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
COMMENTAIRES : GET
https://eu.api.ovh.com/1.0/domain/zone/sydcrc.online/record?fieldType=TXT&subDomain=_acme-challenge.* with 0-byte
payload
COMMENTAIRES : received 2-byte response of content type application/json; charset=utf-8
DÉBOGUER : Record _acme-challenge.*.sydcrc.online with value D9wnCD63eE_R_Aubgn7zhrL2OXr48P25Xe1katZn5FQ doesn't exist.
 Nothing to do.

Confirmer
Voulez-vous continuer cette opération ?
[O] Oui  [T] Oui pour tout  [I] Interrompre la commande  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») :
PS C:\Windows\system32>
```
_______

Still doesn't work, but we can see that there is no trouble to find the domain zone for the unpublish.

**Comment by rmbolger** [comment]
My apologies. I should have mentioned that when using the Publish/Unpublish functions, you don't include the wildcard portion of a name. So for your specific example, just use `sydcrc.online` instead of `*.sydcrc.online`. Normally the `*.` is automatically stripped when called by `New-PACertificate` because that's how the ACME server specifies the challenge record.

**Comment by Naehs** [comment]
Yeah!

Finally, it works!
I had to use unsecured $pArgs and wildcard domain without the "*".

```
$pArgs = @{
    OVHAppKey = 'XXX'
    OVHAppSecretInsecure = 'YYY'
    OVHConsumerKeyInsecure = 'ZZZ'
    OVHRegion = 'ovh-eu'
}
New-PACertificate sydcrc.online -AcceptTOS -Contact support.crc@syd.fr -DnsPlugin OVH -PluginArgs $pArgs
```

Best regards,
Loïc.

**Comment by rmbolger** [comment]
Awesome! Glad to hear things are working now.
