### ISSUE TITLE
Issuing & Renewing a Single Posh-ACME Certificate for Multiple IIS Sites

### ISSUE THREAD

**Issue by abdealipython** [rmbolger/Posh-ACME#601]
We are trying to issue a Posh-ACME certificate for an IIS endpoint and have a requirement where multiple sites on the same server should use the same certificate. We are using multiple SANs (Subject Alternative Names) in the certificate.

How can we issue or renew a single certificate that includes multiple SANs and automatically bind it to multiple IIS sites after issuance/renewal?

Our goal is to have one certificate for the entire server and ensure that, upon issuance or renewal, it is properly bound to all the required IIS sites.

What is the recommended approach to achieve this using Posh-ACME?

**Comment by rmbolger** [comment]
Hi @abdealipython, thanks for reaching out. There are a few different ways you can handle this. The most straightforward way is to use the [Set-IISCertificate](https://docs.dvolve.net/Posh-ACME.Deploy/latest/Functions/Set-IISCertificate/) function which exists in the sister module to this one, [Posh-ACME.Deploy](https://github.com/rmbolger/Posh-ACME.Deploy). This will also require having the version 1.1.0.0+ of the [IISAdministration](https://www.powershellgallery.com/packages/IISAdministration/1.1.0.0) module installed which is only available from the PowerShell gallery. The version built-into Windows is too old unless they updated it on the newest Windows versions.

Essentially your renewal script would look something like this:

```powershell
$cert = Submit-Renewal
if ($cert) {
    $cert | Set-IISCertificate -SiteName "Site1" -OtherParametersAsNecessary
    $cert | Set-IISCertificate -SiteName "Site2" -OtherParametersAsNecessary
    $cert | Set-IISCertificate -SiteName "Site3" -OtherParametersAsNecessary
}
```

There's another way that doesn't require a separate module but is a bit hacky as it takes advantage of a (AFAIK) undocumented feature of IIS's [appcmd.exe](https://learn.microsoft.com/en-us/iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe) that the certificate rebinding feature takes advantage of.

You can essentially run the following to have IIS automatically update certs for any sites matching the given thumbprint.

```
C:\Windows\System32\inetsrv\appcmd.exe renew binding /oldcert:OLDTHUMBPRINT /newcert:NEWTHUMBPRINT
```

So in a renewal script, it might look like this:

```powershell
$oldCert = Get-PACertificate
$cert = Submit-Renewal
if ($cert) {
    & C:\Windows\System32\inetsrv\appcmd.exe renew binding /oldcert:$oldCert.Thumbprint /newcert:$cert.Thumbprint
}
```

I haven't personally tested this in quite a while, but it should theoretically still work.

**Comment by abdealipython** [comment]
I’ve been exploring the Posh-ACME.Deploy module, and the first option seems quite impressive for managing IIS certificate deployments. I’m planning to implement an automated certificate renewal process using this module and would like some insights into its pros and cons beyond the known IISAdministration module dependency (v1.1.0.0+).  

 My Approach:  
- Use "Set-PAAccount -ID $account_id" to set the respective account.  
- Execute "Submit-Renewal" for certificate renewal.  
- Implement a task scheduler job to check daily and renew the certificate when necessary.  
- Bind the renewed certificate using the "Set-IISCertificate"  function 
 My Questions:  
1. Pros & Cons – What are the advantages and potential drawbacks of using Posh-ACME.Deploy for this process, aside from version dependencies?  
2. Please provide insights into other possible reasons for the renewal failure with this module or function?  

Would love to hear your thoughts, especially from those who have implemented something similar. Thanks in advance!

**Comment by rmbolger** [comment]
The only issue I see is the use of `-AllOrder` in the Submit-Renewal command. The rest of the script seems to assume `$cert` will only ever have a single certificate value. But `-AllOrder` makes it seem like you have more than one order to renew. So if you do have more than one and both renew at the same time, your `$cert` value will be an array of objects will will make things like logging `$cert.Subject` weird and it may have an undesirable effect when you pipe it to `Set-IISCertificateOld` (running it twice with the last one "winning" for which cert gets applied).

If you only have a single cert that you're applying to multiple sites, get rid of `-AllOrder` and maybe replace it with a `-Name` or `-MainDomain` parameter to explicitly renew the cert you care about (even if there are multiple saved).

Out of curiosity, why did you end up using Set-IISCertificateOld instead of the newer one? Is it because you didn't want the gallery module dependency?

**Comment by abdealipython** [comment]
Thank you for your response! I truly appreciate your efforts.

We have resolved the issue in our existing environments and are now transitioning to Set-IISCertificate. For the -allorder parameter, we plan to renew only a single certificate, making it our primary focus. I will use the MainDomain or a specific name for future configurations.

It would be great if you could provide insights into the dependencies or prerequisites, particularly for psoh-acme.deploy

**Comment by rmbolger** [comment]
The prereqs for Posh-ACME.Deploy will depend on the functions you choose to use. The module manifest doesn't have any hard dependencies because I didn't want to force people to download modules for functions they weren't planning on using. But to date, I think the only one that has an explicit dependency is the `Set-IISCertificate`. The rest all use stuff that's generally included with Windows or the service they're referencing.

There are no prereqs for Posh-ACME either. It utilizes a relatively common 3rd party encryption library called BouncyCastle. But it comes with the module when you download it from the gallery.

**Comment by abdealipython** [comment]
Thank you for the insight :)

Can you please provide your insight regarding the issue I am facing while executing the following command? When I run it manually, it works fine, but sometimes I encounter the error below while executing submit-renewal. Your insight would be greatly helpful for troubleshooting.


**Powershell Script:-**
try {
    $cert = submit-renewal -MainDomain $certName -ErrorAction Stop
    if (-not $cert) {
        Write-Log "No renewal certificate found. Skipping certificate binding process." -type "INFO"
        exit
    }
    Write-Log "Renewal certificate found: $($cert.Subject). Proceeding with certificate renewal..."
} catch {
    Write-Log "Failed to renew certificate: $_" -type "ERROR"
    exit
}


**Error:-**
Failed to renew certificate: The property 'expires' cannot be found on this object. Verify that the property exists and can be set.

**Comment by abdealipython** [comment]
Also, I'm occasionally encountering the following error while using Posh-ACME:

 **Error :**
2025-03-11 08:00:22 [ERROR] Failed to bind certificate to jwttestcerts_site: Unable to find type [Microsoft.Web.Administration.SslFlags].

**Currently, I am importing the following module:**
Import-Module WebAdministration -ErrorAction Stop -Verbose:$false


**Script:-**
try {
    $sites = Get-Website 
    Write-Log "Total IIS Sites Found: $($sites.Count)"
} catch {
    Write-Log "Error fetching IIS sites: $_" -type "ERROR"
    exit
}

foreach ($site in $sites) {
    $httpsBindings = $site.Bindings.Collection | Where-Object { $_.Protocol -eq "https" }

    foreach ($binding in $httpsBindings) {
        $bindingInfo = $binding.bindingInformation -split ":"
        $ipAddress = if ($bindingInfo[0] -eq "") {"*"} else {$bindingInfo[0]}
        $port = $bindingInfo[1]
        $hostHeader = $bindingInfo[2]

        Write-Log "Binding certificate to Site: $($site.Name) | IP: $ipAddress | Port: $port | Host: $hostHeader"
        try {
            $cert | Set-IISCertificate -SiteName $site.Name -Port $port -HostHeader $hostHeader -IPAddress $ipAddress -Verbose 4>&1 | ForEach-Object { Write-VerboseLog $_ }
            Write-Log "Successfully bound certificate to Site: $($site.Name) | IP: $ipAddress | Port: $port | Host: $hostHeader" -type "SUCCESS"
        } catch {
            Write-Log "Failed to bind certificate to $($site.Name): $_" -type "ERROR"
        }
    }
}

Write-Log "Certificate binding completed!" -type "SUCCESS"

**Comment by abdealipython** [comment]
Hello,  

I am looking forward to your response regarding the issues mentioned below. Please find a summary of my questions:  

1. Failed to Renew Certificate:  
   - Error: "The property 'expires' cannot be found on this object. Verify that the property exists and can be set."  
   - Any insights on this would be greatly appreciated.  

2. Binding Certificate Error:  
   - Error: "2025-03-11 08:00:22 [ERROR] Failed to bind certificate to jwttestcerts_site: Unable to find type [Microsoft.Web.Administration.SslFlags]."  
   - Although we imported the `WebAdministration` module, the issue persisted. However, after adding the following command, it worked successfully:  

   Command:  
   ```powershell
   Add-Type -Path "$env:windir\system32\inetsrv\Microsoft.Web.Administration.dll" -ErrorAction Stop
   ```  
   - Would you consider this a best practice to follow moving forward?  

3. 503 Server Unavailable Error:  
   - Error: "message":"Failed to renew certificate: The remote server returned an error: (503) Server Unavailable.","timestamp":"2025-03-17 20:00:36","type":"ERROR"}  
   - I believe we are using HMAC details for the certificate renewal/issuance. Could this issue be related to our certificate CA being unreachable?  

Your insights on these points would be highly valuable.

**Comment by rmbolger** [comment]
Sorry for the delay. Life has been busy.

The expires error is going to be hard to pinpoint without more context like the full error details or debug output. It might be related to the `-ErrorAction Stop` though. That will treat any error, even benign errors, as a reason to halt which may not be necessary.

The SslFlags error should have been fixed in Posh-ACME.Deploy version 2.0.1. Make sure you're running that version and if it's still a problem, let me know. As a side note, `Set-IISCertificate` relies on the IISAdministration module, not the WebAdministration module. The WebAdministration module and the `Microsoft.Web.Administration.SslFlags` namespace are unrelated.

The 503 error is also going to be hard to pinpoint without more context. It could be the ACME server you're connecting to. It could also be an API server for the validation plugin you're using (assuming you're using a plugin that connects to an API). When you say HMAC details, are you talking about External Account Binding? Or something plugin related?

**Comment by abdealipython** [comment]
Thanks for your response.  
You are correct that our CA was unable to connect at that time, which resulted in the 503 error.  
Additionally, you mentioned that after upgrading **posh-acme.deploy** to version 2.0.1, we are still getting the same issue.  

**Error:**  
{
    "message": "Failed to bind certificate to test_site: Unable to find type [Microsoft.Web.Administration.SslFlags]..Exception.Message",
    "timestamp": "2025-03-22 07:16:42",
    "type": "ERROR"
}


**Version:**  
{
  "output": [
    {
      "Version": "4.28.0",
      "Name": "Posh-ACME"
    },
    {
      "Version": "2.0.1",
      "Name": "Posh-ACME.deploy"
    }
  ]
}


I have only imported the following module in my PowerShell script:  

#powershell
# Import IIS module
try {
    Import-Module IISAdministration -Force
    Write-Log "Successfully imported IISAdministration module"
} catch {
    Write-Log "Failed to initialize IIS modules: $_" -Type "ERROR"
    exit
}

$cert | Set-IISCertificate -SiteName $site.Name -Port $port -HostHeader $hostHeader -IPAddress $ipAddress

**Comment by rmbolger** [comment]
Unfortunately, I'm still not able to reproduce this on any of my systems. Can you verify that the version of the IISAdministration module being loaded is version 1.1.0.0? You might also want to try the same thing in your script that the function does to get the `[Microsoft.Web.Administration.SslFlags]` namespace loaded by making a direct call to one of it's functions like `Get-IISSite`.

So in your script after your Import-Module call, add something like `$null = Get-IISSite`.
